use mimalloc::MiMalloc;
use rustler::{Env, Term};

#[global_allocator]
static GLOBAL: MiMalloc = MiMalloc;

mod dataframe;
mod datatypes;
mod error;
mod series;

use dataframe::*;
pub use datatypes::{ExDataFrame, ExDataFrameRef, ExSeries, ExSeriesRef};
pub use error::ExplorerError;
use series::*;

fn on_load(env: Env, _info: Term) -> bool {
    rustler::resource!(ExDataFrameRef, env);
    rustler::resource!(ExSeriesRef, env);
    true
}

rustler::init!(
    "Elixir.Explorer.PolarsBackend.Native",
    [
        df_as_str,
        df_cast,
        df_clone,
        df_column,
        df_columns,
        df_drop,
        df_drop_duplicates,
        df_drop_nulls,
        df_dtypes,
        df_explode,
        df_fill_none,
        df_filter,
        df_find_idx_by_name,
        df_frame_equal,
        df_get_columns,
        df_head,
        df_height,
        df_hstack,
        df_is_duplicated,
        df_is_unique,
        df_join,
        df_max,
        df_mean,
        df_median,
        df_melt,
        df_min,
        df_n_chunks,
        df_new,
        df_quantile,
        df_read_csv,
        df_read_parquet,
        df_replace,
        df_select,
        df_select_at_idx,
        df_set_column_names,
        df_shape,
        df_shift,
        df_slice,
        df_sort,
        df_stdev,
        df_sum,
        df_tail,
        df_take,
        df_take_with_series,
        df_to_csv_file,
        df_to_dummies,
        df_var,
        df_vstack,
        df_width,
        df_with_column,
        // series
        s_add,
        s_append,
        s_arg_true,
        s_argsort,
        s_as_str,
        s_cast,
        s_clone,
        s_cum_max,
        s_cum_min,
        s_cum_sum,
        s_div,
        s_drop_nulls,
        s_dtype,
        s_eq,
        s_explode,
        s_fill_none,
        s_filter,
        s_get,
        s_gt,
        s_gt_eq,
        s_head,
        s_is_duplicated,
        s_is_not_null,
        s_is_null,
        s_is_unique,
        s_len,
        s_limit,
        s_lt,
        s_lt_eq,
        s_max,
        s_mean,
        s_median,
        s_min,
        s_mul,
        s_n_chunks,
        s_n_unique,
        s_name,
        s_neq,
        s_new_bool,
        s_new_date32,
        s_new_date64,
        s_new_f64,
        s_new_i64,
        s_new_str,
        s_not,
        s_null_count,
        s_peak_max,
        s_peak_min,
        s_pow,
        s_quantile,
        s_rechunk,
        s_rename,
        s_reverse,
        s_rolling_max,
        s_rolling_mean,
        s_rolling_min,
        s_rolling_sum,
        s_seedable_random_indices,
        s_series_equal,
        s_shift,
        s_slice,
        s_sort,
        s_std,
        s_str_contains,
        s_str_lengths,
        s_str_parse_date32,
        s_str_parse_date64,
        s_str_replace,
        s_str_replace_all,
        s_str_to_lowercase,
        s_str_to_uppercase,
        s_sub,
        s_sum,
        s_tail,
        s_take,
        s_take_every,
        s_to_dummies,
        s_to_list,
        s_unique,
        s_var,
        s_value_counts,
        s_zip_with,
    ],
    load = on_load
);
